// Generated by Diagramator from style "GOST" — do not edit, it is overwritten on save.
// Usage: #import "diagram.typ": diagram
//        #diagram()  or  #diagram(scale: 80%)

#let _row(body, align-to: left) = block(width: 100%, height: 13.50pt, inset: (x: 6.00pt), clip: true, align(align-to + horizon, body))
#let _member(t, is-static, is-abstract) = _row({
  set text(style: if is-abstract { "italic" } else { "normal" })
  if is-static { underline(t) } else { t }
})
#let _section(items) = block(width: 100%, inset: (y: 3.00pt), spacing: 0pt, {
  if items.len() == 0 { block(height: 13.50pt) }
  for (t, st, ab) in items { _member(t, st, ab) }
})
#let _badge(letter) = box(baseline: 20%, circle(radius: 5.40pt, fill: rgb("#add1b2"), stroke: 0.75pt + rgb("#000000"), align(center + horizon, text(size: 7.80pt, weight: "bold", letter))))
#let _class(x, y, cw, ch, stereo, name, is-abstract, letter, attrs, methods) = place(dx: x, dy: y, block(
  width: cw, height: ch, stroke: 0.75pt + rgb("#000000"), fill: rgb("#ffffff"), radius: 0.00pt, clip: true, inset: 0.75pt,
  stack(
    block(width: 100%, fill: rgb("#ffffff"), inset: (y: 3.00pt), spacing: 0pt, {
      if stereo != none { _row(align-to: center, text(size: 8.25pt, stereo)) }
      _row(align-to: center, {
        if letter != none { _badge(letter); h(0.3em) }
        text(size: 10.50pt, weight: "bold", style: if is-abstract { "italic" } else { "normal" }, name)
      })
    }),
    block(width: 100%, height: 0.75pt, fill: rgb("#000000")),
    _section(attrs),
    block(width: 100%, height: 0.75pt, fill: rgb("#000000")),
    _section(methods),
  ),
))
#let _edge(dash, ..pts) = {
  let pts = pts.pos()
  for i in range(pts.len() - 1) {
    place(line(start: pts.at(i), end: pts.at(i + 1), stroke: (paint: rgb("#000000"), thickness: 0.75pt, dash: dash)))
  }
}
#let _head(filled, ..pts) = place(polygon(fill: if filled { rgb("#000000") } else { white }, stroke: 0.75pt + rgb("#000000"), ..pts))
#let _open(a, tip, b) = { _edge(none, a, tip); _edge(none, tip, b) }

#let diagram(scale: 100%) = {
  set text(font: ("Times New Roman", "Liberation Serif"), size: 9.75pt, fill: rgb("#000000"), lang: "ru")
  set block(spacing: 0pt)
  let body = box(width: 2049.15pt, height: 799.46pt, {
    _class(3.00pt, 707.96pt, 240.75pt, 88.50pt, none, "shop::Book", false, none, (("- author_: std::string", false, false), ("- pages_: int", false, false)), (("+ Book(sku: std::string, price: Money, author: std::string)", false, false), ("+ weightKg(): double", false, false)))
    _class(3.00pt, 113.96pt, 132.00pt, 88.50pt, none, "shop::Category", false, none, (("- name_: std::string", false, false), ("- parent_: Category*", false, false)), (("+ Category(name: std::string)", false, false), ("+ name(): const std::string&", false, false)))
    _class(222.60pt, 113.96pt, 260.25pt, 88.50pt, none, "shop::Checkout", false, none, (("- policy_: std::unique_ptr<DiscountPolicy>", false, false), ("- catalog_: Repository<Product>*", false, false)), (("+ Checkout(policy: std::unique_ptr<DiscountPolicy>)", false, false), ("+ charge(order: const Order&, customer: Customer&): Money", false, false)))
    _class(582.60pt, 113.96pt, 135.00pt, 75.00pt, none, "shop::Customer", false, none, (("- email_: std::string", false, false),), (("+ Customer(email: std::string)", false, false), ("+ email(): const std::string&", false, false)))
    _class(744.47pt, 3.00pt, 276.00pt, 75.00pt, none, "shop::DiscountPolicy", true, none, (), (("+ ~DiscountPolicy()", false, false), ("+ apply(order: const Order&, amount: double): double {abstract}", false, true)))
    _class(1167.60pt, 113.96pt, 126.75pt, 75.00pt, none, "shop::IPriced", true, none, (), (("+ ~IPriced()", false, false), ("+ price(): double {abstract}", false, true)))
    _class(1381.80pt, 113.96pt, 153.75pt, 75.00pt, none, "shop::IPrintable", true, none, (), (("+ ~IPrintable()", false, false), ("+ describe(): std::string {abstract}", false, true)))
    _class(363.00pt, 707.96pt, 109.50pt, 88.50pt, none, "shop::Laptop", false, none, (("- screenInches_: double", false, false), ("- ramGb_: int", false, false)), (("+ weightKg(): double", false, false), ("+ price(): double", false, false)))
    _class(1639.20pt, 113.96pt, 102.75pt, 88.50pt, "«struct»", "shop::Money", false, none, (("+ cents: long", false, false), ("+ currency: std::string", false, false)), ())
    _class(3.00pt, 455.96pt, 229.50pt, 61.50pt, none, "shop::NoDiscount", false, none, (), (("+ apply(order: const Order&, amount: double): double", false, false),))
    _class(346.80pt, 455.96pt, 234.00pt, 115.50pt, none, "shop::Order", false, none, (("- lines_: std::vector<OrderLine>", false, false), ("- customer_: Customer*", false, false)), (("+ Order(customer: Customer&)", false, false), ("+ addLine(product: const Product&, quantity: int): void", false, false), ("+ total(): double", false, false), ("+ describe(): std::string", false, false)))
    _class(1826.40pt, 113.96pt, 219.75pt, 88.50pt, none, "shop::OrderLine", false, none, (("- product_: const Product*", false, false), ("- quantity_: int", false, false)), (("+ OrderLine(product: const Product&, quantity: int)", false, false), ("+ total(): double", false, false)))
    _class(706.80pt, 455.96pt, 229.50pt, 75.00pt, none, "shop::PercentDiscount", false, none, (("- percent_: double", false, false),), (("+ PercentDiscount(percent: double)", false, false), ("+ apply(order: const Order&, amount: double): double", false, false)))
    _class(1050.60pt, 455.96pt, 194.25pt, 169.50pt, none, "shop::Product", true, none, (("# sku_: std::string", false, false), ("# basePrice_: Money", false, false), ("# category_: std::shared_ptr<Category>", false, false), ("- instances_: int {static}", true, false)), (("+ Product(sku: std::string, basePrice: Money)", false, false), ("+ ~Product()", false, false), ("+ price(): double", false, false), ("+ describe(): std::string", false, false), ("+ weightKg(): double {abstract}", false, true), ("+ instances(): int {static}", true, false)))
    _class(3.00pt, 284.96pt, 181.50pt, 88.50pt, none, "shop::Repository<T>", false, none, (("- items_: std::vector<std::unique_ptr<T>>", false, false),), (("+ add(item: std::unique_ptr<T>): void", false, false), ("+ find(key: const std::string&): T*", false, false), ("+ size(): std::size_t", false, false)))
    _edge(none, (243.75pt, 727.35pt), (1050.60pt, 560.76pt))
    _head(false, (1050.60pt, 560.76pt), (1042.70pt, 566.99pt), (1040.88pt, 558.17pt))
    _edge((4.5pt, 3pt), (240.12pt, 707.96pt), (1639.20pt, 177.68pt))
    _open((1633.74pt, 183.60pt), (1639.20pt, 177.68pt), (1631.19pt, 176.87pt))
    _edge(none, (135.00pt, 131.96pt), (162.00pt, 131.96pt), (162.00pt, 86.96pt), (105.00pt, 86.96pt), (105.00pt, 113.96pt))
    _open((101.40pt, 106.76pt), (105.00pt, 113.96pt), (108.60pt, 106.76pt))
    _edge((4.5pt, 3pt), (482.85pt, 155.25pt), (582.60pt, 152.99pt))
    _open((575.48pt, 156.75pt), (582.60pt, 152.99pt), (575.32pt, 149.55pt))
    _edge(none, (482.85pt, 129.29pt), (744.47pt, 71.16pt))
    _open((738.22pt, 76.24pt), (744.47pt, 71.16pt), (736.66pt, 69.21pt))
    _head(true, (482.85pt, 129.29pt), (489.98pt, 124.02pt), (498.66pt, 125.78pt), (491.54pt, 131.05pt))
    _edge((4.5pt, 3pt), (366.55pt, 202.46pt), (445.76pt, 455.96pt))
    _open((440.17pt, 450.16pt), (445.76pt, 455.96pt), (447.05pt, 448.01pt))
    _edge(none, (444.70pt, 202.46pt), (1050.60pt, 493.98pt))
    _open((1042.55pt, 494.10pt), (1050.60pt, 493.98pt), (1045.67pt, 487.61pt))
    _edge(none, (285.71pt, 202.46pt), (160.77pt, 284.96pt))
    _open((164.79pt, 277.99pt), (160.77pt, 284.96pt), (168.76pt, 283.99pt))
    _edge((4.5pt, 3pt), (482.85pt, 158.21pt), (1639.20pt, 158.21pt))
    _open((1632.00pt, 161.81pt), (1639.20pt, 158.21pt), (1632.00pt, 154.61pt))
    _edge((4.5pt, 3pt), (849.29pt, 78.00pt), (514.89pt, 455.96pt))
    _open((516.97pt, 448.18pt), (514.89pt, 455.96pt), (522.36pt, 452.95pt))
    _edge(none, (472.50pt, 736.34pt), (1050.60pt, 568.85pt))
    _head(false, (1050.60pt, 568.85pt), (1043.21pt, 575.68pt), (1040.70pt, 567.03pt))
    _edge(none, (170.45pt, 455.96pt), (818.20pt, 78.00pt))
    _head(false, (818.20pt, 78.00pt), (812.70pt, 86.42pt), (808.16pt, 78.65pt))
    _edge((4.5pt, 3pt), (232.50pt, 495.66pt), (346.80pt, 504.58pt))
    _open((339.34pt, 507.61pt), (346.80pt, 504.58pt), (339.90pt, 500.43pt))
    _edge(none, (493.50pt, 455.96pt), (630.81pt, 188.96pt))
    _open((630.72pt, 197.01pt), (630.81pt, 188.96pt), (624.32pt, 193.71pt))
    _edge(none, (580.80pt, 471.11pt), (1381.80pt, 179.45pt))
    _head(false, (1381.80pt, 179.45pt), (1374.88pt, 186.76pt), (1371.80pt, 178.30pt))
    _edge(none, (580.80pt, 485.46pt), (1826.40pt, 184.73pt))
    _open((1820.25pt, 189.92pt), (1826.40pt, 184.73pt), (1818.56pt, 182.93pt))
    _head(true, (580.80pt, 485.46pt), (587.83pt, 480.06pt), (596.55pt, 481.66pt), (589.52pt, 487.06pt))
    _edge((4.5pt, 3pt), (580.80pt, 518.33pt), (1050.60pt, 536.87pt))
    _open((1043.26pt, 540.19pt), (1050.60pt, 536.87pt), (1043.55pt, 532.99pt))
    _edge(none, (1845.05pt, 202.46pt), (1244.85pt, 493.60pt))
    _open((1249.76pt, 487.21pt), (1244.85pt, 493.60pt), (1252.90pt, 493.69pt))
    _edge(none, (826.59pt, 455.96pt), (877.43pt, 78.00pt))
    _head(false, (877.43pt, 78.00pt), (880.69pt, 87.52pt), (871.77pt, 86.32pt))
    _edge((4.5pt, 3pt), (706.80pt, 499.95pt), (580.80pt, 507.08pt))
    _open((587.79pt, 503.08pt), (580.80pt, 507.08pt), (588.19pt, 510.27pt))
    _edge(none, (1050.60pt, 506.27pt), (135.00pt, 181.61pt))
    _open((142.99pt, 180.62pt), (135.00pt, 181.61pt), (140.58pt, 187.41pt))
    _edge(none, (1165.85pt, 455.96pt), (1222.95pt, 188.96pt))
    _head(false, (1222.95pt, 188.96pt), (1225.47pt, 198.70pt), (1216.67pt, 196.82pt))
    _edge(none, (1215.43pt, 455.96pt), (1428.72pt, 188.96pt))
    _head(false, (1428.72pt, 188.96pt), (1426.62pt, 198.80pt), (1419.59pt, 193.18pt))
    _edge(none, (1244.85pt, 472.27pt), (1639.20pt, 194.41pt))
    _open((1635.39pt, 201.50pt), (1639.20pt, 194.41pt), (1631.24pt, 195.61pt))
    _head(true, (1244.85pt, 472.27pt), (1249.40pt, 464.66pt), (1258.09pt, 462.94pt), (1253.54pt, 470.55pt))
  })
  if scale == 100% { body } else { std.scale(scale, reflow: true, body) }
}
