// Generated by Diagramator from style "Visual Studio" — do not edit, it is overwritten on save.
// Usage: #import "diagram.typ": diagram
//        #diagram()  or  #diagram(scale: 80%)

#let _row(body, align-to: left) = block(width: 100%, height: 13.50pt, inset: (x: 6.00pt), clip: true, align(align-to + horizon, body))
#let _member(t, is-static, is-abstract) = _row({
  set text(style: if is-abstract { "italic" } else { "normal" })
  if is-static { underline(t) } else { t }
})
#let _section(items) = block(width: 100%, inset: (y: 3.00pt), spacing: 0pt, {
  if items.len() == 0 { block(height: 13.50pt) }
  for (t, st, ab) in items { _member(t, st, ab) }
})
#let _badge(letter) = box(baseline: 20%, circle(radius: 5.40pt, fill: rgb("#d6e2f5"), stroke: 0.75pt + rgb("#7a96c2"), align(center + horizon, text(size: 7.20pt, weight: "bold", letter))))
#let _class(x, y, cw, ch, stereo, name, is-abstract, letter, attrs, methods) = place(dx: x, dy: y, block(
  width: cw, height: ch, stroke: 0.75pt + rgb("#7a96c2"), fill: rgb("#f7f9fc"), radius: 4.50pt, clip: true, inset: 0.75pt,
  stack(
    block(width: 100%, fill: rgb("#d6e2f5"), inset: (y: 3.00pt), spacing: 0pt, {
      if stereo != none { _row(align-to: center, text(size: 8.25pt, stereo)) }
      _row(align-to: center, {
        if letter != none { _badge(letter); h(0.3em) }
        text(size: 9.75pt, weight: "bold", style: if is-abstract { "italic" } else { "normal" }, name)
      })
    }),
    block(width: 100%, height: 0.75pt, fill: rgb("#7a96c2")),
    _section(attrs),
    block(width: 100%, height: 0.75pt, fill: rgb("#7a96c2")),
    _section(methods),
  ),
))
#let _edge(dash, ..pts) = {
  let pts = pts.pos()
  for i in range(pts.len() - 1) {
    place(line(start: pts.at(i), end: pts.at(i + 1), stroke: (paint: rgb("#4d6a99"), thickness: 0.75pt, dash: dash)))
  }
}
#let _head(filled, ..pts) = place(polygon(fill: if filled { rgb("#4d6a99") } else { white }, stroke: 0.75pt + rgb("#4d6a99"), ..pts))
#let _open(a, tip, b) = { _edge(none, a, tip); _edge(none, tip, b) }

#let diagram(scale: 100%) = {
  set text(font: ("Arial", "Liberation Sans"), size: 9.00pt, fill: rgb("#1e1e1e"), lang: "ru")
  set block(spacing: 0pt)
  let body = box(width: 2075.03pt, height: 1033.14pt, {
    _class(31.13pt, 845.32pt, 239.25pt, 88.50pt, none, "shop::Book", false, none, (("- author_: std::string", false, false), ("- pages_: int", false, false)), (("+ Book(sku: std::string, price: Money, author: std::string)", false, false), ("+ weightKg(): double", false, false)))
    _class(3.00pt, 256.95pt, 133.50pt, 88.50pt, none, "shop::Category", false, none, (("- name_: std::string", false, false), ("- parent_: Category*", false, false)), (("+ Category(name: std::string)", false, false), ("+ name(): const std::string&", false, false)))
    _class(630.73pt, 434.52pt, 261.00pt, 88.50pt, none, "shop::Checkout", false, none, (("- policy_: std::unique_ptr<DiscountPolicy>", false, false), ("- catalog_: Repository<Product>*", false, false)), (("+ Checkout(policy: std::unique_ptr<DiscountPolicy>)", false, false), ("+ charge(order: const Order&, customer: Customer&): Money", false, false)))
    _class(610.73pt, 251.32pt, 135.00pt, 75.00pt, none, "shop::Customer", false, none, (("- email_: std::string", false, false),), (("+ Customer(email: std::string)", false, false), ("+ email(): const std::string&", false, false)))
    _class(222.76pt, 60.39pt, 270.75pt, 75.00pt, none, "shop::DiscountPolicy", true, none, (), (("+ ~DiscountPolicy()", false, false), ("+ apply(order: const Order&, amount: double): double {abstract}", false, true)))
    _class(1195.73pt, 251.32pt, 123.00pt, 75.00pt, none, "shop::IPriced", true, none, (), (("+ ~IPriced()", false, false), ("+ price(): double {abstract}", false, true)))
    _class(986.72pt, 289.48pt, 149.25pt, 75.00pt, none, "shop::IPrintable", true, none, (), (("+ ~IPrintable()", false, false), ("+ describe(): std::string {abstract}", false, true)))
    _class(391.13pt, 845.32pt, 113.25pt, 88.50pt, none, "shop::Laptop", false, none, (("- screenInches_: double", false, false), ("- ramGb_: int", false, false)), (("+ weightKg(): double", false, false), ("+ price(): double", false, false)))
    _class(885.09pt, 941.64pt, 103.50pt, 88.50pt, "«struct»", "shop::Money", false, none, (("+ cents: long", false, false), ("+ currency: std::string", false, false)), ())
    _class(31.13pt, 593.32pt, 230.25pt, 61.50pt, none, "shop::NoDiscount", false, none, (), (("+ apply(order: const Order&, amount: double): double", false, false),))
    _class(1357.46pt, 3.00pt, 231.00pt, 115.50pt, none, "shop::Order", false, none, (("- lines_: std::vector<OrderLine>", false, false), ("- customer_: Customer*", false, false)), (("+ Order(customer: Customer&)", false, false), ("+ addLine(product: const Product&, quantity: int): void", false, false), ("+ total(): double", false, false), ("+ describe(): std::string", false, false)))
    _class(1854.53pt, 251.32pt, 217.50pt, 88.50pt, none, "shop::OrderLine", false, none, (("- product_: const Product*", false, false), ("- quantity_: int", false, false)), (("+ OrderLine(product: const Product&, quantity: int)", false, false), ("+ total(): double", false, false)))
    _class(734.93pt, 593.32pt, 230.25pt, 75.00pt, none, "shop::PercentDiscount", false, none, (("- percent_: double", false, false),), (("+ PercentDiscount(percent: double)", false, false), ("+ apply(order: const Order&, amount: double): double", false, false)))
    _class(1078.73pt, 593.32pt, 196.50pt, 169.50pt, none, "shop::Product", true, none, (("# sku_: std::string", false, false), ("# basePrice_: Money", false, false), ("# category_: std::shared_ptr<Category>", false, false), ("- instances_: int {static}", true, false)), (("+ Product(sku: std::string, basePrice: Money)", false, false), ("+ ~Product()", false, false), ("+ price(): double", false, false), ("+ describe(): std::string", false, false), ("+ weightKg(): double {abstract}", false, true), ("+ instances(): int {static}", true, false)))
    _class(31.13pt, 422.32pt, 181.50pt, 88.50pt, none, "shop::Repository<T>", false, none, (("- items_: std::vector<std::unique_ptr<T>>", false, false),), (("+ add(item: std::unique_ptr<T>): void", false, false), ("+ find(key: const std::string&): T*", false, false), ("+ size(): std::size_t", false, false)))
    _edge(none, (270.38pt, 864.92pt), (1078.73pt, 698.32pt))
    _head(false, (1078.73pt, 698.32pt), (1070.82pt, 704.55pt), (1069.00pt, 695.73pt))
    _edge((4.5pt, 3pt), (270.38pt, 904.23pt), (885.09pt, 979.54pt))
    _open((877.50pt, 982.24pt), (885.09pt, 979.54pt), (878.38pt, 975.10pt))
    _edge(none, (136.50pt, 274.95pt), (163.50pt, 274.95pt), (163.50pt, 229.95pt), (106.50pt, 229.95pt), (106.50pt, 256.95pt))
    _open((102.90pt, 249.75pt), (106.50pt, 256.95pt), (110.10pt, 249.75pt))
    _edge((4.5pt, 3pt), (741.89pt, 434.52pt), (694.61pt, 326.32pt))
    _open((700.80pt, 331.48pt), (694.61pt, 326.32pt), (694.20pt, 334.36pt))
    _edge(none, (714.40pt, 434.52pt), (397.82pt, 135.39pt))
    _open((405.52pt, 137.72pt), (397.82pt, 135.39pt), (400.58pt, 142.95pt))
    _head(true, (714.40pt, 434.52pt), (706.04pt, 431.57pt), (702.62pt, 423.39pt), (710.98pt, 426.34pt))
    _edge((4.5pt, 3pt), (836.57pt, 434.52pt), (1374.63pt, 118.50pt))
    _open((1370.25pt, 125.25pt), (1374.63pt, 118.50pt), (1366.60pt, 119.04pt))
    _edge(none, (853.53pt, 523.02pt), (1078.73pt, 630.97pt))
    _open((1070.68pt, 631.11pt), (1078.73pt, 630.97pt), (1073.79pt, 624.62pt))
    _edge(none, (630.73pt, 476.28pt), (212.63pt, 468.30pt))
    _open((219.90pt, 464.84pt), (212.63pt, 468.30pt), (219.76pt, 472.04pt))
    _edge((4.5pt, 3pt), (776.55pt, 523.02pt), (921.52pt, 941.64pt))
    _open((915.76pt, 936.01pt), (921.52pt, 941.64pt), (922.56pt, 933.65pt))
    _edge((4.5pt, 3pt), (493.51pt, 93.38pt), (1357.46pt, 64.60pt))
    _open((1350.38pt, 68.44pt), (1357.46pt, 64.60pt), (1350.14pt, 61.24pt))
    _edge(none, (504.38pt, 873.15pt), (1078.73pt, 706.57pt))
    _head(false, (1078.73pt, 706.57pt), (1071.34pt, 713.40pt), (1068.83pt, 704.75pt))
    _edge(none, (158.63pt, 593.32pt), (343.03pt, 135.39pt))
    _head(false, (343.03pt, 135.39pt), (343.84pt, 145.42pt), (335.49pt, 142.06pt))
    _edge((4.5pt, 3pt), (218.67pt, 593.32pt), (1357.46pt, 109.79pt))
    _open((1352.24pt, 115.92pt), (1357.46pt, 109.79pt), (1349.43pt, 109.29pt))
    _edge(none, (1357.46pt, 93.90pt), (745.73pt, 269.45pt))
    _open((751.66pt, 264.00pt), (745.73pt, 269.45pt), (753.64pt, 270.93pt))
    _edge(none, (1383.67pt, 118.50pt), (1119.32pt, 289.48pt))
    _head(false, (1119.32pt, 289.48pt), (1124.44pt, 280.81pt), (1129.33pt, 288.37pt))
    _edge(none, (1588.46pt, 116.07pt), (1870.88pt, 251.32pt))
    _open((1862.83pt, 251.46pt), (1870.88pt, 251.32pt), (1865.94pt, 244.97pt))
    _head(true, (1588.46pt, 116.07pt), (1597.32pt, 116.32pt), (1603.07pt, 123.06pt), (1594.21pt, 122.81pt))
    _edge((4.5pt, 3pt), (1445.27pt, 118.50pt), (1217.61pt, 593.32pt))
    _open((1217.48pt, 585.27pt), (1217.61pt, 593.32pt), (1223.97pt, 588.39pt))
    _edge(none, (1872.31pt, 339.82pt), (1275.23pt, 630.28pt))
    _open((1280.13pt, 623.89pt), (1275.23pt, 630.28pt), (1283.28pt, 630.37pt))
    _edge(none, (815.44pt, 593.32pt), (392.74pt, 135.39pt))
    _head(false, (392.74pt, 135.39pt), (402.16pt, 138.95pt), (395.54pt, 145.05pt))
    _edge((4.5pt, 3pt), (891.03pt, 593.32pt), (1409.86pt, 118.50pt))
    _open((1406.98pt, 126.02pt), (1409.86pt, 118.50pt), (1402.12pt, 120.71pt))
    _edge(none, (1078.73pt, 644.63pt), (136.50pt, 323.92pt))
    _open((144.48pt, 322.83pt), (136.50pt, 323.92pt), (142.16pt, 329.65pt))
    _edge(none, (1194.45pt, 593.32pt), (1249.50pt, 326.32pt))
    _head(false, (1249.50pt, 326.32pt), (1252.09pt, 336.05pt), (1243.27pt, 334.23pt))
    _edge(none, (1149.07pt, 593.32pt), (1073.70pt, 364.48pt))
    _head(false, (1073.70pt, 364.48pt), (1080.79pt, 371.62pt), (1072.24pt, 374.44pt))
    _edge(none, (1110.86pt, 762.82pt), (971.36pt, 941.64pt))
    _open((972.95pt, 933.74pt), (971.36pt, 941.64pt), (978.63pt, 938.17pt))
    _head(true, (1110.86pt, 762.82pt), (1108.72pt, 771.42pt), (1100.90pt, 775.60pt), (1103.04pt, 766.99pt))
  })
  if scale == 100% { body } else { std.scale(scale, reflow: true, body) }
}
