//! Typst exporter: renders a laid-out [`Diagram`] with a [`StyleProfile`] into a
//! standalone `.typ` module exposing `#let diagram(scale: 100%)`.
//!
//! Geometry mirrors the editor exactly: class boxes use the IR position/size,
//! rows have fixed heights from the style, and edges use the same border-clipping
//! as `src/entities/diagram/ui/FloatingEdge.tsx`.

use std::fmt::Write;

use crate::ir::{ClassKind, ClassNode, Diagram, RelationType};
use crate::style::{StyleProfile, PX_TO_PT};

/// Self-relation loop size, same as `LOOP` in `FloatingEdge.tsx`.
const LOOP: f64 = 36.0;
/// Space around the drawing so arrowheads and loops are not clipped.
const MARGIN: f64 = 4.0;

#[derive(Clone, Copy)]
struct P {
    x: f64,
    y: f64,
}

struct Rect {
    x: f64,
    y: f64,
    w: f64,
    h: f64,
}

impl Rect {
    fn of(c: &ClassNode) -> Self {
        let p = &c.position;
        Self { x: p.x, y: p.y, w: p.width, h: p.height }
    }

    /// Point where the line from this rect's center towards `b`'s center leaves this rect.
    fn border_point(&self, b: &Rect) -> P {
        let (cx, cy) = (self.x + self.w / 2.0, self.y + self.h / 2.0);
        let dx = b.x + b.w / 2.0 - cx;
        let dy = b.y + b.h / 2.0 - cy;
        if dx == 0.0 && dy == 0.0 {
            return P { x: cx, y: cy };
        }
        let tx = if dx == 0.0 { f64::INFINITY } else { self.w / 2.0 / dx.abs() };
        let ty = if dy == 0.0 { f64::INFINITY } else { self.h / 2.0 / dy.abs() };
        let t = tx.min(ty);
        P { x: cx + dx * t, y: cy + dy * t }
    }
}

enum Head {
    None,
    HollowTriangle,
    FilledDiamond,
    HollowDiamond,
    OpenArrow,
}

/// UML notation per relation kind: (dashed, head at source, head at target).
/// Must match `EDGE_STYLES` in `src/entities/diagram/lib/toFlow.ts`.
fn notation(kind: RelationType) -> (bool, Head, Head) {
    use RelationType::*;
    match kind {
        Inheritance => (false, Head::None, Head::HollowTriangle),
        Realization => (true, Head::None, Head::HollowTriangle),
        Composition => (false, Head::FilledDiamond, Head::OpenArrow),
        Aggregation => (false, Head::HollowDiamond, Head::OpenArrow),
        Association => (false, Head::None, Head::OpenArrow),
        Dependency => (true, Head::None, Head::OpenArrow),
    }
}

fn stereotype(kind: ClassKind) -> Option<&'static str> {
    match kind {
        ClassKind::Interface => Some("«interface»"),
        ClassKind::Struct => Some("«struct»"),
        ClassKind::Enum => Some("«enumeration»"),
        ClassKind::Union => Some("«union»"),
        ClassKind::Class => None,
    }
}

fn badge(kind: ClassKind) -> &'static str {
    match kind {
        ClassKind::Class => "C",
        ClassKind::Struct => "S",
        ClassKind::Interface => "I",
        ClassKind::Enum => "E",
        ClassKind::Union => "U",
    }
}

fn is_abstract(c: &ClassNode) -> bool {
    c.kind == ClassKind::Interface || c.methods.iter().any(|m| m.contains("{abstract}"))
}

/// Typst string literal.
fn lit(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => {}
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Editor px → Typst length.
fn pt(px: f64) -> String {
    format!("{:.2}pt", px * PX_TO_PT)
}

fn point(p: P, origin: P) -> String {
    format!("({}, {})", pt(p.x - origin.x), pt(p.y - origin.y))
}

pub fn render(diagram: &Diagram, style: &StyleProfile) -> String {
    let s = style;
    let c = &s.colors;
    let fonts: Vec<String> = s
        .font
        .iter()
        .filter(|f| !matches!(f.as_str(), "serif" | "sans-serif" | "monospace"))
        .map(|f| lit(f))
        .collect();
    let stroke = format!("{} + rgb({})", pt(s.border_width), lit(&c.border));
    let edge_stroke = format!("{} + rgb({})", pt(s.edge_width), lit(&c.edge));

    let mut out = String::new();
    let _ = writeln!(
        out,
        "// Generated by Diagramator from style \"{}\" — do not edit, it is overwritten on save.\n\
         // Usage: #import \"diagram.typ\": diagram\n//        #diagram()  or  #diagram(scale: 80%)\n",
        s.name.replace('\n', " ")
    );
    // Shared helpers keep the per-class output small.
    let _ = writeln!(
        out,
        r#"#let _row(body, align-to: left) = block(width: 100%, height: {lh}, inset: (x: {px}), clip: true, align(align-to + horizon, body))
#let _member(t, is-static, is-abstract) = _row({{
  set text(style: if is-abstract {{ "italic" }} else {{ "normal" }})
  if is-static {{ underline(t) }} else {{ t }}
}})
#let _section(items) = block(width: 100%, inset: (y: {py}), spacing: 0pt, {{
  if items.len() == 0 {{ block(height: {lh}) }}
  for (t, st, ab) in items {{ _member(t, st, ab) }}
}})
#let _badge(letter) = box(baseline: 20%, circle(radius: {br}, fill: rgb({badge}), stroke: {bstroke}, align(center + horizon, text(size: {bsize}, weight: "bold", letter))))
#let _class(x, y, cw, ch, stereo, name, is-abstract, letter, attrs, methods) = place(dx: x, dy: y, block(
  width: cw, height: ch, stroke: {stroke}, fill: rgb({fill}), radius: {radius}, clip: true, inset: {bw},
  stack(
    block(width: 100%, fill: rgb({hfill}), inset: (y: {py}), spacing: 0pt, {{
      if stereo != none {{ _row(align-to: center, text(size: {ssize}, stereo)) }}
      _row(align-to: center, {{
        if letter != none {{ _badge(letter); h(0.3em) }}
        text(size: {nsize}, weight: {weight}, style: if is-abstract {{ "italic" }} else {{ "normal" }}, name)
      }})
    }}),
    block(width: 100%, height: {bw}, fill: rgb({border})),
    _section(attrs),
    block(width: 100%, height: {bw}, fill: rgb({border})),
    _section(methods),
  ),
))
#let _edge(dash, ..pts) = {{
  let pts = pts.pos()
  for i in range(pts.len() - 1) {{
    place(line(start: pts.at(i), end: pts.at(i + 1), stroke: (paint: rgb({edge}), thickness: {ew}, dash: dash)))
  }}
}}
#let _head(filled, ..pts) = place(polygon(fill: if filled {{ rgb({edge}) }} else {{ white }}, stroke: {estroke}, ..pts))
#let _open(a, tip, b) = {{ _edge(none, a, tip); _edge(none, tip, b) }}
"#,
        lh = pt(s.line_height),
        px = pt(s.padding_x),
        py = pt(s.padding_y),
        br = pt(s.line_height * 0.4),
        badge = lit(&c.badge),
        bstroke = stroke,
        bsize = pt(s.font_size * 0.8),
        stroke = stroke,
        fill = lit(&c.fill),
        hfill = lit(&c.header_fill),
        radius = pt(s.corner_radius),
        ssize = pt(s.stereotype_font_size),
        nsize = pt(s.name_font_size),
        weight = lit(if s.name_bold { "bold" } else { "regular" }),
        edge = lit(&c.edge),
        ew = pt(s.edge_width),
        estroke = edge_stroke,
        bw = pt(s.border_width),
        border = lit(&c.border),
    );

    // Everything is drawn relative to the diagram's top-left corner.
    let rects: Vec<Rect> = diagram.classes.iter().map(Rect::of).collect();
    let has_loop = |id: &str| diagram.relations.iter().any(|r| r.source == id && r.target == id);
    let (mut min, mut max) = (P { x: f64::MAX, y: f64::MAX }, P { x: f64::MIN, y: f64::MIN });
    for (cls, r) in diagram.classes.iter().zip(&rects) {
        let extra = if has_loop(&cls.id) { LOOP + s.arrow_size } else { 0.0 };
        min.x = min.x.min(r.x);
        min.y = min.y.min(r.y - extra);
        max.x = max.x.max(r.x + r.w + extra);
        max.y = max.y.max(r.y + r.h);
    }
    if diagram.classes.is_empty() {
        min = P { x: 0.0, y: 0.0 };
        max = min;
    }
    let origin = P { x: min.x - MARGIN, y: min.y - MARGIN };
    let (width, height) = (max.x - min.x + 2.0 * MARGIN, max.y - min.y + 2.0 * MARGIN);

    let _ = writeln!(out, "#let diagram(scale: 100%) = {{");
    let _ = writeln!(
        out,
        "  set text(font: ({}), size: {}, fill: rgb({}), lang: \"ru\")\n  set block(spacing: 0pt)",
        fonts.join(", ") + if fonts.len() == 1 { "," } else { "" },
        pt(s.font_size),
        lit(&c.text)
    );
    let _ = writeln!(out, "  let body = box(width: {}, height: {}, {{", pt(width), pt(height));

    for (cls, r) in diagram.classes.iter().zip(&rects) {
        let members = |items: &[String]| -> String {
            let parts: Vec<String> = items
                .iter()
                .map(|m| format!("({}, {}, {})", lit(m), m.ends_with("{static}"), m.contains("{abstract}")))
                .collect();
            // Trailing comma keeps one-element arrays arrays.
            format!("({}{})", parts.join(", "), if parts.len() == 1 { "," } else { "" })
        };
        let _ = writeln!(
            out,
            "    _class({}, {}, {}, {}, {}, {}, {}, {}, {}, {})",
            pt(r.x - origin.x),
            pt(r.y - origin.y),
            pt(r.w),
            pt(r.h),
            stereotype(cls.kind).map_or("none".into(), lit),
            lit(&cls.name),
            is_abstract(cls),
            if s.kind_badge { lit(badge(cls.kind)) } else { "none".into() },
            members(&cls.attributes),
            members(&cls.methods),
        );
    }

    let index = |id: &str| diagram.classes.iter().position(|c| c.id == id);
    for rel in &diagram.relations {
        let (Some(si), Some(ti)) = (index(&rel.source), index(&rel.target)) else {
            continue;
        };
        let (dashed, head_s, head_t) = notation(rel.kind);
        let dash = if dashed { "(4.5pt, 3pt)" } else { "none" };
        let src = &rects[si];
        // Polyline from source to target; heads are drawn at the first/last point.
        let pts: Vec<P> = if si == ti {
            let right = src.x + src.w;
            let start_y = src.y + 24f64.min(src.h / 3.0);
            let end_x = right - 40f64.min(src.w / 4.0);
            vec![
                P { x: right, y: start_y },
                P { x: right + LOOP, y: start_y },
                P { x: right + LOOP, y: src.y - LOOP },
                P { x: end_x, y: src.y - LOOP },
                P { x: end_x, y: src.y },
            ]
        } else {
            let dst = &rects[ti];
            vec![src.border_point(dst), dst.border_point(src)]
        };
        let pts_str: Vec<String> = pts.iter().map(|&p| point(p, origin)).collect();
        let _ = writeln!(out, "    _edge({}, {})", dash, pts_str.join(", "));
        let n = pts.len();
        head(&mut out, &head_t, pts[n - 2], pts[n - 1], s.arrow_size, origin);
        head(&mut out, &head_s, pts[1], pts[0], s.arrow_size, origin);
    }

    let _ = writeln!(out, "  }})");
    let _ = writeln!(out, "  if scale == 100% {{ body }} else {{ std.scale(scale, reflow: true, body) }}");
    let _ = writeln!(out, "}}");
    out
}

/// Arrowhead at `tip`, for a segment arriving from `from`.
fn head(out: &mut String, kind: &Head, from: P, tip: P, size: f64, origin: P) {
    let (dx, dy) = (tip.x - from.x, tip.y - from.y);
    let len = (dx * dx + dy * dy).sqrt();
    if len == 0.0 {
        return;
    }
    let (ux, uy) = (dx / len, dy / len);
    let (nx, ny) = (-uy, ux);
    // Point `back` along the edge and `side` across it, measured from the tip.
    let at = |back: f64, side: f64| point(P { x: tip.x - ux * back + nx * side, y: tip.y - uy * back + ny * side }, origin);
    let l = size;
    let _ = match kind {
        Head::None => Ok(()),
        Head::HollowTriangle => writeln!(out, "    _head(false, {}, {}, {})", point(tip, origin), at(l, l / 2.0), at(l, -l / 2.0)),
        Head::FilledDiamond | Head::HollowDiamond => writeln!(
            out,
            "    _head({}, {}, {}, {}, {})",
            matches!(kind, Head::FilledDiamond),
            point(tip, origin),
            at(l * 0.9, l * 0.4),
            at(l * 1.8, 0.0),
            at(l * 0.9, -l * 0.4)
        ),
        Head::OpenArrow => writeln!(out, "    _open({}, {}, {})", at(l * 0.8, l * 0.4), point(tip, origin), at(l * 0.8, -l * 0.4)),
    };
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{Position, Relation};
    use crate::style::PRESETS;
    use std::path::Path;

    fn sample() -> Diagram {
        let class = |id: &str, name: &str, kind, x, y| ClassNode {
            id: id.into(),
            name: name.into(),
            kind,
            attributes: vec!["- name: \"quoted\" \\ string".into(), "+ count: int {static}".into()],
            methods: vec!["+ area(): double {abstract}".into()],
            position: Position { x, y, width: 200.0, height: 120.0 },
        };
        Diagram {
            classes: vec![
                class("a", "Shape", ClassKind::Interface, 0.0, 0.0),
                class("b", "Circle", ClassKind::Class, 0.0, 250.0),
                class("c", "Точка", ClassKind::Struct, 300.0, 250.0),
            ],
            relations: vec![
                Relation { source: "b".into(), target: "a".into(), kind: RelationType::Realization },
                Relation { source: "b".into(), target: "c".into(), kind: RelationType::Composition },
                Relation { source: "c".into(), target: "c".into(), kind: RelationType::Aggregation },
                Relation { source: "c".into(), target: "a".into(), kind: RelationType::Dependency },
            ],
        }
    }

    /// Compiles the output with the real `typst` CLI for every preset; skipped if typst is missing.
    #[test]
    fn compiles_with_typst() {
        let typst = std::env::var("TYPST").unwrap_or_else(|_| "typst".into());
        if std::process::Command::new(&typst).arg("--version").output().is_err() {
            eprintln!("typst not found; skipping");
            return;
        }
        // Output is kept for eyeballing: target/typst-preview/<preset>.pdf
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../target/typst-preview");
        for (name, json) in PRESETS {
            let style = StyleProfile::from_json(json).unwrap();
            let dir = root.join(name);
            std::fs::create_dir_all(&dir).unwrap();
            std::fs::write(dir.join("diagram.typ"), render(&sample(), &style)).unwrap();
            let main = dir.join("main.typ");
            std::fs::write(&main, "#set page(width: auto, height: auto, margin: 10pt)\n#import \"diagram.typ\": diagram\n#diagram()\n#diagram(scale: 50%)\n").unwrap();
            let out = std::process::Command::new(&typst)
                .arg("compile")
                .arg(&main)
                .arg(root.join(format!("{name}.png")))
                .arg("--ppi=110")
                .output()
                .unwrap();
            assert!(out.status.success(), "{name}: {}", String::from_utf8_lossy(&out.stderr));
        }
    }

    #[test]
    fn escapes_strings() {
        assert_eq!(lit(r#"a"b\c"#), r#""a\"b\\c""#);
    }
}
